apiVersion: v1
kind: Pod
metadata:
  name: consumer
  namespace: my-namespace
  labels:
    app: consumer-app
spec:
  containers:
    - name: consumer-container
      image: consumer:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8081
      envFrom:
        - secretRef:
            name: my-secret
        - configMapRef:
            name: my-config
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"