apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  namespace: my-namespace
data:
  DATABASE_HOST: "mariadb-external.my-namespace.svc.cluster.local"
  DATABASE_PORT: "3306"
  DATABASE_NAME: "k8s_db"
  DATABASE_USER: "k8s_user"
  CONSUMER_HOST: "consumer-service"
  CONSUMER_PORT: "8081"
  PRODUCER_HOST: "producer-service"
  PRODUCER_PORT: "8080"