services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: r00t_P@assword
      MYSQL_DATABASE: k8s_db
      MYSQL_USER: k8s_user
      MYSQL_PASSWORD: k8s_secret_P@assword
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_bridge_network

networks:
  my_bridge_network:
    driver: bridge