# DNS Record for localhost outside the k8s cluster
apiVersion: v1
kind: Service
metadata:
  name: mariadb-external
  namespace: my-namespace
spec:
  type: ExternalName
  externalName: "host.minikube.internal"
---
# Create NodePort service for Consumer
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  namespace: my-namespace
spec:
  selector:
    app: consumer-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30000
  type: NodePort
---
# Create NodePort service for Producer
apiVersion: v1
kind: Service
metadata:
  name: producer-service
  namespace: my-namespace
spec:
  selector:
    app: producer-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
  type: NodePort